# Generated by Django 3.1.12 on 2026-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
