# Generated by Django 3.1.12 on 2026-07-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('PATIENT_ADMISSIONS', 'Patient Admissions'), ('DISCHARGES', 'Discharges'), ('INVENTORY', 'Inventory'), ('STAFF_ATTENDANCE', 'Staff Attendance'), ('FINANCIALS', 'Financials')], max_length=30)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], default='PDF', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('PATIENT_DEMOGRAPHICS', 'Patient Demographics'), ('APPOINTMENT_TRENDS', 'Appointment Trends'), ('HEALTH_OUTCOMES', 'Health Outcomes')], max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(help_text='Chart-ready aggregated data, e.g. series/labels/values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('metric_type', 'period_start', 'period_end')},
            },
        ),
    ]
